### ISSUE TITLE
Please ensure your Github credentials are secure

### ISSUE THREAD

**Issue by hannahwhy** [ArchiveTeam/things-to-do#1]
You've probably all heard about Heartbleed and OpenSSL, so I won't belabor that point.

The real point: I'd like to make sure that ArchiveTeam organization owners have taken steps to secure their Github credentials.  As the ArchiveTeam organization was created in the vulnerability window, it is possible that all owners' credentials have been compromised.

Github has patched their systems (see https://github.com/blog/1818-security-heartbleed-vulnerability), so now would be a good time to (at the very least) reset your password.

Please respond to this issue with either:
1. a notification that your credentials are secure
2. a wish to be removed from the owners list

Thanks.

**Comment by hannahwhy** [comment]
If I don't hear back from owners within a week, I'll remove them from the owner group.  Nothing personal, just paranoia.

**Comment by hannahwhy** [comment]
FYI: This message is intended for organization owners only.  If you're not an owner and are getting these messages, I apologize.

**Comment by ivan** [comment]
ArchiveTeam organization owners should also
1. change the password for the email account associated with their GitHub account
2. if that email address is on their own domain, change passwords on the domain registrar and DNS provider.

GitHub also provides two-factor authentication: https://github.com/blog/1614-two-factor-authentication

**Comment by NotActuallyTerry** [comment]
I've changed my password, and enabled 2FA. Keep me on the list.

**Comment by chfoo** [comment]
I changed my GitHub and Gmail password and 2FA is also enabled for both. Please keep me on the list.

**Comment by db48x** [comment]
Done.

**Comment by ae-s** [comment]
I have enabled 2FA for GitHub, and changed passwords corresponding to the following services: github, email, dns, domain registrar.

**Comment by soult** [comment]
Done.

**Comment by ivan** [comment]
> I have enabled 2FA for GitHub, and changed passwords corresponding to the following services: github, email, dns, domain registrar.

I have done the same.

**Comment by DopefishJustin** [comment]
Changed

**Comment by coderjo** [comment]
Passwords changed on github and email.

**Comment by hannahwhy** [comment]
☑ Github credentials changed
☑ Mail credentials changed
☑ Registrar credentials changed
☑ DNS credentials changed
☐ https://twitter.com/Pinboard/status/453621970454581249

**Comment by hannahwhy** [comment]
This issue is almost 7 days old.  When it hits 7 days old, I'll cull the admin list.

(If you get around to checking your email too late: no problem, just secure your credentials, make a comment here, and we can fix the situation.)

**Comment by hannahwhy** [comment]
Cull complete.

**Comment by kimmel** [comment]
Sorry I am late. I changed my passwords.

**Comment by ersi** [comment]
Checking in late - but credentials have been changed days ago. :-)

**Comment by hannahwhy** [comment]
How do I know that you aren't impostors using someone else's credentials :fearful: :exclamation:

(Nah, it doesn't really matter -- worst thing one could do is introduce bogus commits...)

@kimmel, @ersi: access restored.
